name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        wasi_sdk_version:
        - major: 11
          minor: 0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang bits
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{ matrix.wasi_sdk_version.major }}/wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}-linux.tar.gz
        tar xvf wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}-linux.tar.gz
    - name: Build
      run: make WASI_SDK=wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}
