name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  ACR_NAME: itowlsonacrwasm

jobs:
  build:
    strategy:
      matrix:
        wasi_sdk_version:
        - major: 11
          minor: 0

    name: Build release assets

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang bits
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{ matrix.wasi_sdk_version.major }}/wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}-linux.tar.gz
        tar xvf wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}-linux.tar.gz

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "name=RELEASE_VERSION::canary" >> $GITHUB_ENV

    - name: Build release
      run: make WASI_SDK=wasi-sdk-${{ matrix.wasi_sdk_version.major }}.${{ matrix.wasi_sdk_version.minor }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: cwasm.wasm
        path: ./cwasm.wasm

  publish:
    name: Push released module to OCI registry
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Install wasm-to-oci
      run: |
        mkdir tools
        wget https://github.com/engineerd/wasm-to-oci/releases/download/v0.1.1/linux-amd64-wasm-to-oci -q -O ./tools/wasm-to-oci
        chmod +x ./tools/wasm-to-oci

    - name: Set the release version
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version
      if: github.ref == 'refs/heads/main'
      run: echo "name=RELEASE_VERSION::canary" >> $GITHUB_ENV

    - name: Download release assets
      uses: actions/download-artifact@v1
      with:
        name: cwasm.wasm
        path: ./assets

    - name: Log into registry
      run: az acr login -n ${ACR_NAME} -u ${{ secrets.ACR_SP_ID }} -p ${{ secrets.ACR_SP_PASSWORD }}

    - name: Publish to registry
      run: ./tools/wasm-to-oci push ./assets/cwasm.wasm ${ACR_NAME}.azurecr.io/cwasm:${RELEASE_VERSION}
